name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-py@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -U pip
      - run: pip install hatch
      - run: hatch run fmt
      - run: hatch run lint
      - run: hatch run typechcek
      - run: hatch run cov
      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
        continue-on-error: true